export const SET_GOOGLE_CONFIG = 'SET_GOOGLE_CONFIG'
export const GET_GOOGLE_SIGNIN = 'GET_GOOGLE_SIGNIN';

export const SET_GOOGLE_USER = 'SET_GOOGLE_USER';
export const SET_LOGIN_RESPONSE = 'SET_LOGIN_RESPONSE';
export const SET_LOGIN_INDICATOR = 'SET_LOGIN_INDICATOR';

export const SET_BACKEND = 'SET_BACKEND';
export const SET_BACKEND_ITEMSREF = 'SET_BACKEND_ITEMSREF';
export const SET_BACKEND_USER = 'SET_BACKEND_USER';
export const SET_BACKEND_USERREF = 'SET_BACKEND_USERREF';

export const SET_USER_TRIPS = 'SET_USER_TRIPS';
export const SET_USER_TRIPS_FETCHING = 'SET_USER_TRIPS_FETCHING';

export const SET_CURRENT_TRIP = 'SET_CURRENT_TRIP';
export const SET_CURRENT_TRIP_FETCHING = 'SET_CURRENT_TRIP_FETCHING';

export const SET_ORIENTATION = 'SET_ORIENTATION';


